# Generated by Django 5.0.1 on 2024-02-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_business_interested_life_categories_and_more'),
        ('testimonials', '0002_servicepackage_business_delete_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
