# Generated by Django 5.0.1 on 2024-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcreator',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
