# Generated by Django 5.0.1 on 2024-02-06 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_business_completed_and_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
